import { MENU_ID } from '@/lib/menu/config';

export const ACCESS_LEVEL = {
    EXCLUDE_AUTH: 0,
    AUTHENTICATED: 1,
    VIEW_PERMISSION: 2,
    MANAGE_PERMISSION: 3,
} as const;

export type AccessLevel = typeof ACCESS_LEVEL[keyof typeof ACCESS_LEVEL];

export const PAGE_PERMISSION_TYPE = {
    VIEW: 'VIEW',
    MANAGE: 'MANAGE',
} as const;

export type PagePermissionType = typeof PAGE_PERMISSION_TYPE[keyof typeof PAGE_PERMISSION_TYPE];

export interface AccessInfo {
    referenceRouteNames: string[];
}

// backend data format of page permissions. page includes wildcard('*').
export interface RawPagePermission {
    page: string;
    permission: PagePermissionType;
}

// refined page permission types. page NEVER includes wildcard.
export type PagePermissionMap = Record<string, PagePermissionType>;

export type PagePermissionTuple = [page: string, permission: PagePermissionType];

export const PROJECT_USER_DEFAULT_PERMISSIONS: PagePermissionTuple[] = [
    [MENU_ID.HOME_DASHBOARD, PAGE_PERMISSION_TYPE.VIEW],
    [MENU_ID.MY_PAGE, PAGE_PERMISSION_TYPE.MANAGE],
    [MENU_ID.MY_PAGE_ACCOUNT, PAGE_PERMISSION_TYPE.MANAGE],
    [MENU_ID.MY_PAGE_ACCOUNT_PROFILE, PAGE_PERMISSION_TYPE.MANAGE],
    [MENU_ID.MY_PAGE_NOTIFICATIONS, PAGE_PERMISSION_TYPE.MANAGE],
    [MENU_ID.MY_PAGE_API_KEY, PAGE_PERMISSION_TYPE.MANAGE],
    [MENU_ID.INFO, PAGE_PERMISSION_TYPE.VIEW],
    [MENU_ID.INFO_NOTICE, PAGE_PERMISSION_TYPE.VIEW],
];
export const ADMIN_USER_DEFAULT_PERMISSIONS: PagePermissionTuple[] = [
    [MENU_ID.HOME_DASHBOARD, PAGE_PERMISSION_TYPE.VIEW],
    [MENU_ID.MY_PAGE, PAGE_PERMISSION_TYPE.MANAGE],
    [MENU_ID.MY_PAGE_ACCOUNT, PAGE_PERMISSION_TYPE.MANAGE],
    [MENU_ID.MY_PAGE_ACCOUNT_PROFILE, PAGE_PERMISSION_TYPE.MANAGE],
    [MENU_ID.MY_PAGE_NOTIFICATIONS, PAGE_PERMISSION_TYPE.MANAGE],
    [MENU_ID.MY_PAGE_API_KEY, PAGE_PERMISSION_TYPE.MANAGE],
    [MENU_ID.INFO, PAGE_PERMISSION_TYPE.MANAGE],
    [MENU_ID.INFO_NOTICE, PAGE_PERMISSION_TYPE.MANAGE],
];
export const SYSTEM_USER_DEFAULT_PERMISSIONS: PagePermissionTuple[] = [
    [MENU_ID.ADMINISTRATION, PAGE_PERMISSION_TYPE.MANAGE],
    [MENU_ID.ADMINISTRATION_IAM, PAGE_PERMISSION_TYPE.MANAGE],
    [MENU_ID.ADMINISTRATION_ROLE, PAGE_PERMISSION_TYPE.MANAGE],
    [MENU_ID.ADMINISTRATION_POLICY, PAGE_PERMISSION_TYPE.MANAGE],
    [MENU_ID.ADMINISTRATION_USER, PAGE_PERMISSION_TYPE.MANAGE],
    [MENU_ID.MY_PAGE, PAGE_PERMISSION_TYPE.MANAGE],
    [MENU_ID.MY_PAGE_ACCOUNT, PAGE_PERMISSION_TYPE.MANAGE],
    [MENU_ID.MY_PAGE_ACCOUNT_PROFILE, PAGE_PERMISSION_TYPE.MANAGE],
    [MENU_ID.MY_PAGE_API_KEY, PAGE_PERMISSION_TYPE.MANAGE],
    [MENU_ID.INFO, PAGE_PERMISSION_TYPE.MANAGE],
    [MENU_ID.INFO_NOTICE, PAGE_PERMISSION_TYPE.MANAGE],
];
export const NO_ROLE_USER_DEFAULT_PERMISSIONS: PagePermissionTuple[] = [
    [MENU_ID.MY_PAGE, PAGE_PERMISSION_TYPE.VIEW],
    [MENU_ID.MY_PAGE_ACCOUNT, PAGE_PERMISSION_TYPE.VIEW],
    [MENU_ID.MY_PAGE_ACCOUNT_PROFILE, PAGE_PERMISSION_TYPE.MANAGE],
];
export const DOMAIN_OWNER_DEFAULT_PERMISSIONS: PagePermissionTuple[] = [
    [MENU_ID.ADMINISTRATION, PAGE_PERMISSION_TYPE.MANAGE],
    [MENU_ID.ADMINISTRATION_IAM, PAGE_PERMISSION_TYPE.MANAGE],
    [MENU_ID.ADMINISTRATION_ROLE, PAGE_PERMISSION_TYPE.MANAGE],
    [MENU_ID.ADMINISTRATION_POLICY, PAGE_PERMISSION_TYPE.MANAGE],
    [MENU_ID.ADMINISTRATION_USER, PAGE_PERMISSION_TYPE.MANAGE],
    [MENU_ID.MY_PAGE, PAGE_PERMISSION_TYPE.MANAGE],
    [MENU_ID.MY_PAGE_ACCOUNT, PAGE_PERMISSION_TYPE.MANAGE],
    [MENU_ID.MY_PAGE_ACCOUNT_PROFILE, PAGE_PERMISSION_TYPE.MANAGE],
    [MENU_ID.INFO, PAGE_PERMISSION_TYPE.VIEW],
    [MENU_ID.INFO_NOTICE, PAGE_PERMISSION_TYPE.VIEW],
];
