module.exports = {
    extends: [
        'stylelint-config-standard',
        'stylelint-config-recommended-vue',
    ],
    rules: {
        'selector-pseudo-element-no-unknown': [true, { ignorePseudoElements: ['v-deep', 'deep'] }],
        'selector-pseudo-class-no-unknown': [true, { ignorePseudoClasses: ['deep'] }],
        indentation: [4, { baseIndentLevel: 0 }],
        'declaration-empty-line-before': null,
        'at-rule-no-unknown': [true, { ignoreAtRules: ['define-mixin', 'mixin', 'at', 'screen', 'tailwind'] }],
        'rule-empty-line-before': null,
        'selector-list-comma-newline-after': null,
        'no-descending-specificity': null,
        'declaration-block-no-redundant-longhand-properties': null,
        'font-family-name-quotes': null,
        'value-keyword-case': null,
        'import-notation': 'string',
        'selector-not-notation': 'simple',
        'selector-class-pattern': null,
        'property-no-vendor-prefix': null,
        'number-max-precision': null,
        'color-function-notation': null,
        'function-no-unknown': null,
        'property-no-unknown': [true, { ignoreProperties: [/\$(.+?)/] }],
    },
};
