{{ if .Values.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.name }}-nginx
  namespace: {{ .Values.global.namespace | default .Release.Namespace }}
data:
  wconsole-client.conf: |-
{{ .Files.Get "config/wconsole-client.conf" | nindent 4 }}
{{ end }}
