export const NOTIFICATION_PROTOCOL_STATE = {
    ENABLED: 'ENABLED',
    DISABLED: 'DISABLED',
} as const;

export const NOTIFICATION_PROTOCOL_PLUGIN_UPGRADE_MODE = {
    AUTO: 'AUTO',
    MANUAL: 'MANUAL',
} as const;
