// SCOPE
export const DASHBOARD_SCOPE_ENTIRE = 'ENTIRE';
export const DASHBOARD_SCOPE_SINGLE = 'SINGLE';

// VIEWER
export const DASHBOARD_VIEWER_PUBLIC = 'PUBLIC';
export const DASHBOARD_VIEWER_PRIVATE = 'PRIVATE';
