import type { Icon } from '@/common/modules/widgets/_widget-fields/icon/type';

export const ICON_FIELD_ITEMS: Icon[] = [
    { name: 'ic_circle-filled', label: 'Circle' },
    { name: 'ic_coin-filled', label: 'Coin' },
    { name: 'ic_yen-filled', label: 'Yen' },
    { name: 'ic_won-filled', label: 'Won' },
    { name: 'ic_lock-filled', label: 'Lock' },
    { name: 'ic_spanner-filled', label: 'Spanner' },
    { name: 'ic_home-filled', label: 'Home' },
    { name: 'ic_rocket-filled', label: 'Rocket' },
    { name: 'ic_error-filled', label: 'Error' },
    { name: 'ic_limit-filled', label: 'Limit' },
    { name: 'ic_megaphone-filled', label: 'Megaphone' },
    { name: 'ic_warning-filled', label: 'Warning' },
    { name: 'ic_sparkle-filled', label: 'Sparkle' },
    { name: 'ic_arrow-right-up-with-sparkles', label: 'Arrow Right-up with sparkles' },
    { name: 'ic_service_metric-explorer', label: 'Gauge' },
    { name: 'ic_service_cloud-service', label: 'Cloud' },
    { name: 'ic_service_project', label: 'Planet' },
    { name: 'ic_service_budget', label: 'Budget' },
    { name: 'ic_service_cost-report', label: 'Budget Report' },
    { name: 'ic_service_server', label: 'Server' },
    { name: 'ic_private-repository', label: 'Private Repository' },
    { name: 'ic_service_data-sources', label: 'Data Source' },
    { name: 'ic_service_alert-dashboard', label: 'Monitor' },
    { name: 'ic_service_alert', label: 'Notice' },
    { name: 'ic_service_user', label: 'User' },
    { name: 'ic_service_escalation-policy', label: 'Escalation' },
    { name: 'ic_service_workspaces', label: 'Cube' },
    { name: 'ic_service_domain-settings', label: 'Settings' },
    { name: 'ic_service_security', label: 'Security Lock' },
    { name: 'ic_my-page_account-and-profile', label: 'Authorization' },
    { name: 'ic_service_service-account', label: 'Security key' },
];
