export const REFERENCE_TYPE_MAP = {
    app: 'app',
    cloudServiceType: 'cloud_service_type',
    cloudServiceQuerySet: 'cloud_service_query_set',
    collector: 'collector',
    costDataSource: 'cost_data_source',
    escalationPolicy: 'escalation_policy',
    metric: 'metric',
    namespace: 'namespace',
    plugin: 'plugin',
    projectGroup: 'project_group',
    project: 'project',
    protocol: 'protocol',
    provider: 'provider',
    publicDashboard: 'public_dashboard',
    publicFolder: 'public_folder',
    region: 'region',
    role: 'role',
    secret: 'secret',
    serviceAccount: 'service_account',
    service: 'service',
    trustedServiceAccount: 'trusted_service_account',
    userGroup: 'user_group',
    user: 'user',
    webhook: 'webhook',
    workspaceGroup: 'workspace_group',
    workspace: 'workspace',
} as const;
