import type { MenuId } from '@/lib/menu/config';
import { MENU_ID } from '@/lib/menu/config';

export const ACCESS_LEVEL = {
    EXCLUDE_AUTH: 0,
    AUTHENTICATED: 1,
    VIEW_PERMISSION: 2,
    MANAGE_PERMISSION: 3,
    ADMIN_PERMISSION: 4,
} as const;

export type AccessLevel = typeof ACCESS_LEVEL[keyof typeof ACCESS_LEVEL];

export const PAGE_PERMISSION_TYPE = {
    VIEW: 'VIEW',
    MANAGE: 'MANAGE',
} as const;

export type PagePermissionType = typeof PAGE_PERMISSION_TYPE[keyof typeof PAGE_PERMISSION_TYPE];

export interface PagePermission {
    page: string;
    permission: PagePermissionType;
}


export interface AccessInfo {
    referenceMenuIds: MenuId[];
}

// refined page permission types. page NEVER includes wildcard.
export type PagePermissionMap = Record<string, PagePermissionType>;

export type PagePermissionTuple = [page: string, permission: PagePermissionType];

export const BASIC_USER_DEFAULT_PERMISSIONS: PagePermissionTuple[] = [
    [MENU_ID.HOME_DASHBOARD, PAGE_PERMISSION_TYPE.VIEW],
    [MENU_ID.MY_PAGE, PAGE_PERMISSION_TYPE.MANAGE],
    [MENU_ID.ACCOUNT, PAGE_PERMISSION_TYPE.MANAGE],
    [MENU_ID.ACCOUNT_PROFILE, PAGE_PERMISSION_TYPE.MANAGE],
    [MENU_ID.NOTIFICATIONS, PAGE_PERMISSION_TYPE.MANAGE],
    [MENU_ID.API_KEY, PAGE_PERMISSION_TYPE.MANAGE],
    [MENU_ID.INFO, PAGE_PERMISSION_TYPE.VIEW],
    [MENU_ID.NOTICE, PAGE_PERMISSION_TYPE.VIEW],
];

// TODO: this need to be changed with new SYSTEM domain planning
export const SYSTEM_USER_DEFAULT_PERMISSIONS: PagePermissionTuple[] = [
    [MENU_ID.ADMINISTRATION, PAGE_PERMISSION_TYPE.MANAGE],
    [MENU_ID.IAM, PAGE_PERMISSION_TYPE.MANAGE],
    [MENU_ID.ROLE, PAGE_PERMISSION_TYPE.MANAGE],
    [MENU_ID.APP, PAGE_PERMISSION_TYPE.MANAGE],
    [MENU_ID.USER, PAGE_PERMISSION_TYPE.MANAGE],
    [MENU_ID.MY_PAGE, PAGE_PERMISSION_TYPE.MANAGE],
    [MENU_ID.ACCOUNT, PAGE_PERMISSION_TYPE.MANAGE],
    [MENU_ID.ACCOUNT_PROFILE, PAGE_PERMISSION_TYPE.MANAGE],
    [MENU_ID.API_KEY, PAGE_PERMISSION_TYPE.MANAGE],
    [MENU_ID.INFO, PAGE_PERMISSION_TYPE.MANAGE],
    [MENU_ID.NOTICE, PAGE_PERMISSION_TYPE.MANAGE],
];
export const NO_ROLE_USER_DEFAULT_PERMISSIONS: PagePermissionTuple[] = [
    [MENU_ID.MY_PAGE, PAGE_PERMISSION_TYPE.VIEW],
    [MENU_ID.ACCOUNT, PAGE_PERMISSION_TYPE.VIEW],
    [MENU_ID.ACCOUNT_PROFILE, PAGE_PERMISSION_TYPE.MANAGE],
];
export const DOMAIN_ADMIN_DEFAULT_PERMISSIONS: PagePermissionTuple[] = [
    // TODO: add all page
    [MENU_ID.HOME_DASHBOARD, PAGE_PERMISSION_TYPE.VIEW],
    [MENU_ID.ADMINISTRATION, PAGE_PERMISSION_TYPE.MANAGE],
    [MENU_ID.IAM, PAGE_PERMISSION_TYPE.MANAGE],
    [MENU_ID.ROLE, PAGE_PERMISSION_TYPE.MANAGE],
    [MENU_ID.APP, PAGE_PERMISSION_TYPE.MANAGE],
    [MENU_ID.USER, PAGE_PERMISSION_TYPE.MANAGE],
    [MENU_ID.PREFERENCE, PAGE_PERMISSION_TYPE.MANAGE],
    [MENU_ID.WORKSPACES, PAGE_PERMISSION_TYPE.MANAGE],
    [MENU_ID.DOMAIN_SETTINGS, PAGE_PERMISSION_TYPE.MANAGE],
    [MENU_ID.MY_PAGE, PAGE_PERMISSION_TYPE.MANAGE],
    [MENU_ID.ACCOUNT, PAGE_PERMISSION_TYPE.MANAGE],
    [MENU_ID.ACCOUNT_PROFILE, PAGE_PERMISSION_TYPE.MANAGE],
    [MENU_ID.INFO, PAGE_PERMISSION_TYPE.VIEW],
    [MENU_ID.NOTICE, PAGE_PERMISSION_TYPE.VIEW],
];
