/**
 * 🚀 AUTO-GENERATED API DOCUMENTATION
 *
 * This file is **automatically generated** by the API documentation script.
 * **DO NOT** modify this file manually, as changes will be overwritten.
 *
 * ## Purpose:
 * - Provides a structured mapping of API endpoints based on the directory structure.
 * - Used for **query key generation**, **caching strategies**, and **API reference**.
 * - Helps maintain consistency and prevents hardcoded API keys.
 *
 * ## How It Works:
 * - The script scans the `api-clients/{service-name}/{resource-name}/schema/api-verbs/` directory.
 * - Extracts `{service-name}`, `{resource-name}`, and `{verb}.ts` files.
 * - Generates a structured **API_DOC** constant.
 *
 * ## Regenerate:
 * If you need to update this file, run:
 *
 * ```sh
 * npm run api-doc
 * ```
 *
 * 🚨 Any manual modifications will be lost on regeneration!
 */

export const API_DOC = {
    'alert-manager': {
        alert: [
            'create',
            'delete',
            'get',
            'history',
            'list',
            'update',
        ],
        'escalation-policy': [
            'create',
            'delete',
            'get',
            'list',
            'update',
        ],
        event: [
            'create',
        ],
        'event-rule': [
            'change-order',
            'create',
            'delete',
            'get',
            'list',
            'update',
        ],
        note: [
            'create',
            'delete',
            'get',
            'list',
            'update',
        ],
        'notification-protocol': [
            'create',
            'delete',
            'disable',
            'enable',
            'get',
            'list',
            'update-plugin',
            'update',
            'verify-plugin',
        ],
        service: [
            'change-members',
            'create',
            'delete',
            'get',
            'list',
            'update',
        ],
        'service-channel': [
            'create-forward-channel',
            'create',
            'delete',
            'disable',
            'enable',
            'get',
            'list',
            'update',
        ],
        'user-channel': [
            'create',
            'delete',
            'disable',
            'enable',
            'get',
            'list',
            'update',
        ],
        'user-group-channel': [
            'create',
            'delete',
            'disable',
            'enable',
            'get',
            'list',
            'update',
        ],
        webhook: [
            'create',
            'delete',
            'disable',
            'enable',
            'get',
            'list-errors',
            'list',
            'update-message-format',
            'update-plugin',
            'update',
            'verify-plugin',
        ],
    },
    config: {
        'domain-config': [
            'create',
            'get',
            'list',
            'set',
            'update',
        ],
        'public-config': [
            'create',
            'delete',
            'get',
            'list',
            'set',
            'update',
        ],
        'shared-config': [
            'create',
            'delete',
            'get',
            'list',
            'update',
        ],
        'user-config': [
            'create',
            'delete',
            'get',
            'list',
            'set',
            'update',
        ],
    },
    'cost-analysis': {
        budget: [
            'create',
            'delete',
            'get',
            'list',
            'set-notification',
            'update',
        ],
        'budget-usage': [
            'analyze',
            'list',
        ],
        cost: [
            'analyze',
            'stat',
        ],
        'cost-query-set': [
            'create',
            'delete',
            'list',
            'update',
        ],
        'cost-report': [
            'get-url',
            'get',
            'list',
            'send',
        ],
        'cost-report-config': [
            'list',
            'run',
            'update-recipients',
            'update',
        ],
        'cost-report-data': [
            'analyze',
            'list',
        ],
        'data-source': [
            'get',
            'list',
            'sync',
            'update-permissions',
        ],
        'data-source-account': [
            'analyze',
            'list',
            'reset',
            'update',
        ],
        job: [
            'cancel',
            'list',
        ],
        'report-adjustment': [
            'change-order',
            'create',
            'delete',
            'get',
            'list',
            'update',
        ],
        'report-adjustment-policy': [
            'change-order',
            'create',
            'delete',
            'get',
            'list',
            'sync-currency',
            'update',
        ],
        'unified-cost': [
            'analyze',
            'get',
            'list',
            'stat',
        ],
    },
    dashboard: {
        'private-dashboard': [
            'change-folder',
            'create',
            'delete',
            'get',
            'list',
            'update',
        ],
        'private-data-table': [
            'add',
            'delete',
            'get',
            'list',
            'load',
            'transform',
            'update',
        ],
        'private-folder': [
            'create',
            'delete',
            'get',
            'list',
            'update',
        ],
        'private-widget': [
            'create',
            'delete',
            'get',
            'list',
            'load-sum',
            'load',
            'update',
        ],
        'public-dashboard': [
            'change-folder',
            'create',
            'delete',
            'get',
            'list',
            'share',
            'unshare',
            'update',
        ],
        'public-data-table': [
            'add',
            'delete',
            'get',
            'list',
            'load',
            'transform',
            'update',
        ],
        'public-folder': [
            'create',
            'delete',
            'get',
            'list',
            'share',
            'unshare',
            'update',
        ],
        'public-widget': [
            'create',
            'delete',
            'get',
            'list',
            'load-sum',
            'load',
            'update',
        ],
    },
    identity: {
        agent: [
            'create',
            'delete',
            'disable',
            'enable',
            'get',
            'list',
            'regenerate',
        ],
        app: [
            'create',
            'delete',
            'disable',
            'enable',
            'generateApiKey',
            'get',
            'list',
            'stat',
            'update',
        ],
        domain: [
            'get-auth-info',
            'get',
            'list',
        ],
        endpoint: [
            'list',
        ],
        job: [
            'delete',
            'get',
            'list',
            'stat',
        ],
        package: [
            'change-order',
            'create',
            'delete',
            'get',
            'list',
            'set-default',
            'update',
        ],
        project: [
            'add-users',
            'change-project-group',
            'create',
            'delete',
            'get',
            'list',
            'remove-users',
            'udpate',
            'update-project-type',
        ],
        'project-group': [
            'add-users',
            'change-parent-group',
            'create',
            'delete',
            'get',
            'list',
            'remove-users',
            'update',
        ],
        provider: [
            'create',
            'delete',
            'get',
            'list',
            'stat',
            'update',
        ],
        role: [
            'create',
            'delete',
            'disable',
            'enable',
            'get',
            'list-basic-role',
            'list',
            'update',
        ],
        'role-binding': [
            'create',
            'delete',
            'list',
            'update-role',
        ],
        schema: [
            'create',
            'delete',
            'get',
            'list',
            'stat',
            'update',
        ],
        'service-account': [
            'create',
            'detele-secret-data',
            'detele',
            'get',
            'list',
            'stat',
            'update-secret-data',
            'update',
        ],
        token: [
            'grant',
            'issue',
        ],
        'trusted-account': [
            'create',
            'detele',
            'get',
            'list',
            'stat',
            'update-secret-data',
            'update',
        ],
        user: [
            'create',
            'delete',
            'disable-mfa',
            'disable',
            'enable',
            'get',
            'list',
            'update',
            'verify-email',
        ],
        'user-group': [
            'add-users',
            'create',
            'delete',
            'get',
            'list',
            'remove-users',
            'update',
        ],
        'user-profile': [
            'confirm-email',
            'confirm-mfa',
            'enable-mfa',
            'get-workspaces',
            'reset-password',
            'update-password',
            'update',
            'verify-email',
        ],
        workspace: [
            'add-package',
            'change-workspace-group',
            'create',
            'delete',
            'list',
            'remove-package',
            'update',
        ],
        'workspace-group': [
            'add-users',
            'create',
            'delete',
            'get',
            'list',
            'remove-users',
            'stat',
            'update-role',
            'update',
        ],
        'workspace-group-user': [
            'add',
            'find',
            'get',
            'list',
            'remove',
            'stat',
            'update-role',
        ],
        'workspace-user': [
            'create',
            'find',
            'get',
            'list',
        ],
    },
    inventory: {
        'cloud-service-type': [
            'list',
            'stat',
        ],
        collector: [
            'collect',
            'create',
            'delete',
            'get',
            'list',
            'update-plugin',
            'update',
        ],
        metric: [
            'create',
            'delete',
            'get',
            'list',
            'run',
            'update',
        ],
        'metric-data': [
            'analyze',
        ],
        namespace: [
            'get',
            'list',
        ],
        region: [
            'list',
        ],
    },
    notification: {
        protocol: [
            'create',
            'delete',
            'disable',
            'enable',
            'get',
            'list',
            'update-plugin',
            'update',
        ],
    },
    monitoring: {
        alert: [
            'assign-user',
            'create',
            'delete',
            'get',
            'list',
            'update-state',
            'update',
        ],
        'data-source': [
            'list',
        ],
        'escalation-policy': [
            'create',
            'delete',
            'get',
            'list',
            'set-default',
            'update',
        ],
        event: [
            'list',
        ],
        'event-rule': [
            'change-order',
            'create',
            'delete',
            'get',
            'list',
            'update',
        ],
        log: [
            'list',
        ],
        note: [
            'create',
            'delete',
            'get',
            'list',
            'update',
        ],
        'project-alert-config': [
            'create',
            'delete',
            'get',
            'list',
            'update',
        ],
        webhook: [
            'create',
            'delete',
            'disable',
            'enable',
            'get',
            'list',
            'update-plugin',
            'update',
            'verify-plugin',
        ],
    },
    notification: {
        protocol: [
            'create',
            'delete',
            'disable',
            'enable',
            'get',
            'list',
            'update-plugin',
            'update',
        ],
    },
    opsflow: {
        comment: [
            'create',
            'delete',
            'get',
            'list',
            'update',
        ],
        event: [
            'list',
        ],
        task: [
            'change-assignee',
            'change-status',
            'create',
            'delete',
            'get',
            'list',
            'update-description',
            'update',
        ],
        'task-category': [
            'create',
            'delete',
            'get',
            'list',
            'update',
        ],
        'task-type': [
            'create',
            'delete',
            'get',
            'list',
            'update-fields',
            'update',
        ],
    },
    repository: {
        'dashboard-template': [
            'list',
            'register',
        ],
        plugin: [
            'deregister',
            'disable',
            'enable',
            'get-versions',
            'get',
            'list',
            'register',
            'stat',
            'update',
        ],
    },
    secret: {
        secret: [
            'create',
            'get',
            'list',
        ],
    },
} as const;
export type APIDoc = typeof API_DOC;
