import { MENU_ID } from '@/lib/menu/config';

export const ALERT_MANAGER_ROUTE = Object.freeze({
    _NAME: MENU_ID.ALERT_MANAGER,
    DASHBOARD: { _NAME: MENU_ID.ALERT_MANAGER_DASHBOARD },
    ALERT: {
        _NAME: MENU_ID.ALERT_MANAGER_ALERT,
        DETAIL: { _NAME: `${MENU_ID.ALERT_MANAGER_ALERT}.detail` },
    },
    ESCALATION_POLICY: { _NAME: MENU_ID.ALERT_MANAGER_ESCALATION_POLICY },
});
