export const RESOURCE_CONFIG_MAP = {
    project: {
        name: 'Project',
        resourceKey: 'project',
        idKey: 'project_id',
        nameKey: 'name',
    },
    projectGroup: {
        name: 'Project Group',
        resourceKey: 'projectGroup',
        idKey: 'project_group_id',
        nameKey: 'name',
    },
    workspace: {
        name: 'Workspace',
        resourceKey: 'workspace',
        idKey: 'workspace_id',
        nameKey: 'name',
    },
    workspaceGroup: {
        name: 'Workspace Group',
        resourceKey: 'workspaceGroup',
        idKey: 'workspace_group_id',
        nameKey: 'name',
    },
    app: {
        name: 'App',
        resourceKey: 'app',
        idKey: 'app_id',
        nameKey: 'name',
    },
    cloudServiceType: {
        name: 'Cloud Service Type',
        resourceKey: 'cloudServiceType',
        idKey: 'cloud_service_type_id',
        nameKey: 'name',
    },
    cloudServiceQuerySet: {
        name: 'Cloud Service Query Set',
        resourceKey: 'cloudServiceQuerySet',
        idKey: 'query_set_id',
        nameKey: 'name',
    },
    collector: {
        name: 'Collector',
        resourceKey: 'collector',
        idKey: 'collector_id',
        nameKey: 'name',
    },
    costDataSource: {
        name: 'Cost Data Source',
        resourceKey: 'costDataSource',
        idKey: 'data_source_id',
        nameKey: 'name',
    },
    role: {
        name: 'Role',
        resourceKey: 'role',
        idKey: 'role_id',
        nameKey: 'name',
    },
    region: {
        name: 'Region',
        resourceKey: 'region',
        idKey: 'region_code',
        nameKey: 'name',
    },
    secret: {
        name: 'Secret',
        resourceKey: 'secret',
        idKey: 'secret_id',
        nameKey: 'name',
    },
    provider: {
        name: 'Provider',
        resourceKey: 'provider',
        idKey: 'provider',
        nameKey: 'name',
    },
    serviceAccount: {
        name: 'Service Account',
        resourceKey: 'serviceAccount',
        idKey: 'service_account_id',
        nameKey: 'name',
    },
    trustedAccount: {
        name: 'Trusted Account',
        resourceKey: 'trustedAccount',
        idKey: 'trusted_account_id',
        nameKey: 'name',
    },
    user: {
        name: 'User',
        resourceKey: 'user',
        idKey: 'user_id',
        nameKey: 'name',
    },
    userGroup: {
        name: 'User Group',
        resourceKey: 'userGroup',
        idKey: 'user_group_id',
        nameKey: 'name',
    },
    protocol: {
        name: 'Protocol',
        resourceKey: 'protocol',
        idKey: 'protocol_id',
        nameKey: 'name',
    },
    webhook: {
        name: 'Webhook',
        resourceKey: 'webhook',
        idKey: 'webhook_id',
        nameKey: 'name',
    },
    service: {
        name: 'Service',
        resourceKey: 'service',
        idKey: 'service_id',
        nameKey: 'name',
    },
    escalationPolicy: {
        name: 'Escalation Policy',
        resourceKey: 'escalationPolicy',
        idKey: 'escalation_policy_id',
        nameKey: 'name',
    },
    metric: {
        name: 'Metric',
        resourceKey: 'metric',
        idKey: 'metric_id',
        nameKey: 'name',
    },
    namespace: {
        name: 'Namespace',
        resourceKey: 'namespace',
        idKey: 'namespace_id',
        nameKey: 'name',
    },
    plugin: {
        name: 'Plugin',
        resourceKey: 'plugin',
        idKey: 'plugin_id',
        nameKey: 'name',
    },
} as const;
