export const ROLE_TYPE = {
    SYSTEM: 'SYSTEM',
    SYSTEM_ADMIN: 'SYSTEM_ADMIN',
    DOMAIN_ADMIN: 'DOMAIN_ADMIN',
    WORKSPACE_OWNER: 'WORKSPACE_OWNER',
    WORKSPACE_MEMBER: 'WORKSPACE_MEMBER',
} as const;
