export const ROLE_TYPE = {
    SYSTEM_ADMIN: 'SYSTEM_ADMIN',
    DOMAIN_ADMIN: 'DOMAIN_ADMIN',
    WORKSPACE_OWNER: 'WORKSPACE_OWNER',
    WORKSPACE_MEMBER: 'WORKSPACE_MEMBER',
    USER: 'USER',
} as const;

export const ROLE_STATE = {
    ENABLED: 'ENABLED',
    DISABLED: 'DISABLED',
} as const;
