export const SERVICE_FEATURES = {
    DASHBOARDS: 'DASHBOARDS',
    PROJECT: 'PROJECT',
    SERVICE_ACCOUNT: 'SERVICE_ACCOUNT',
    ASSET_INVENTORY: 'ASSET_INVENTORY',
    COST_EXPLORER: 'COST_EXPLORER',
    ALERT_MANAGER: 'ALERT_MANAGER',
    OPS_FLOW: 'OPS_FLOW',
    IAM: 'IAM',
} as const;

export const DEFAULT_VERSION = 'V1';

export const DEFAULT_CONFIG = {
    DASHBOARDS: {
        ENABLED: true,
        VERSION: DEFAULT_VERSION,
    },
    PROJECT: {
        ENABLED: true,
        VERSION: DEFAULT_VERSION,
    },
    SERVICE_ACCOUNT: {
        ENABLED: true,
        VERSION: DEFAULT_VERSION,
    },
    ASSET_INVENTORY: {
        ENABLED: true,
        VERSION: DEFAULT_VERSION,
    },
    COST_ANALYSIS: {
        ENABLED: true,
        VERSION: DEFAULT_VERSION,
    },
    ALERT_MANAGER: {
        ENABLED: true,
        VERSION: DEFAULT_VERSION,
    },
};
