export const SERVICE_FEATURES = {
    DASHBOARDS: 'DASHBOARDS',
    PROJECT: 'PROJECT',
    SERVICE_ACCOUNT: 'SERVICE_ACCOUNT',
    ASSET_INVENTORY: 'ASSET_INVENTORY',
    COST_EXPLORER: 'COST_EXPLORER',
    ALERT_MANAGER: 'ALERT_MANAGER',
    OPS_FLOW: 'OPS_FLOW',
    IAM: 'IAM',
} as const;
