
export const GLOBAL_VARIABLE_FILTER_TYPE_MAP = {
    REFERENCE: 'REFERENCE',
    ENUM: 'ENUM',
    TEXT_INPUT: 'TEXT_INPUT',
    NUMBER_INPUT: 'NUMBER_INPUT',
    NUMBER_SLIDER: 'NUMBER_SLIDER',
} as const;

