
import * as actions from './actions';
import * as getters from './getters';
import * as mutations from './mutations';
import type { DashboardState } from './type';

// TODO: implementation
const state: DashboardState = {
    domainItems: [
        {
            domain_dashboard_id: '123',
            name: 'Cafe Gondry',
            version: 0,
            viewers: 'PUBLIC',
            labels: ['Chicken', 'Hop', 'Pub'],
            tags: {},
            user_id: '',
            domain_id: '',
            settings: {},
            dashboard_options: {},
            dashboard_options_schema: {},
            layouts: [],
            created_at: '',
            updated_at: '',
        },
        {
            domain_dashboard_id: '123',
            name: 'Cafe Gondry2',
            version: 0,
            viewers: 'PRIVATE',
            labels: ['Hop', 'Pub'],
            tags: {},
            user_id: '',
            domain_id: '',
            settings: {},
            dashboard_options: {},
            dashboard_options_schema: {},
            layouts: [],
            created_at: '',
            updated_at: '',
        },
        {
            domain_dashboard_id: '1231',
            name: 'Cafe Gondry21',
            version: 0,
            viewers: 'PRIVATE',
            labels: ['Hop', 'Pub'],
            tags: {},
            user_id: '',
            domain_id: '',
            settings: {},
            dashboard_options: {},
            dashboard_options_schema: {},
            layouts: [],
            created_at: '',
            updated_at: '',
        },
        {
            domain_dashboard_id: '1232',
            name: 'Cafe Gondry22',
            version: 0,
            viewers: 'PRIVATE',
            labels: ['Hop', 'Pub'],
            tags: {},
            user_id: '',
            domain_id: '',
            settings: {},
            dashboard_options: {},
            dashboard_options_schema: {},
            layouts: [],
            created_at: '',
            updated_at: '',
        },
        {
            domain_dashboard_id: '1233',
            name: 'Cafe Gondry23',
            version: 0,
            viewers: 'PRIVATE',
            labels: ['Hop', 'Pub'],
            tags: {},
            user_id: '',
            domain_id: '',
            settings: {},
            dashboard_options: {},
            dashboard_options_schema: {},
            layouts: [],
            created_at: '',
            updated_at: '',
        },
        {
            domain_dashboard_id: '1234',
            name: 'Cafe Gondry24',
            version: 0,
            viewers: 'PRIVATE',
            labels: ['Hop', 'Pub'],
            tags: {},
            user_id: '',
            domain_id: '',
            settings: {},
            dashboard_options: {},
            dashboard_options_schema: {},
            layouts: [],
            created_at: '',
            updated_at: '',
        },
        {
            domain_dashboard_id: '1235',
            name: 'Cafe Gondry25',
            version: 0,
            viewers: 'PRIVATE',
            labels: ['Hop', 'Pub'],
            tags: {},
            user_id: '',
            domain_id: '',
            settings: {},
            dashboard_options: {},
            dashboard_options_schema: {},
            layouts: [],
            created_at: '',
            updated_at: '',
        },
        {
            domain_dashboard_id: '1236',
            name: 'Cafe Gondry26',
            version: 0,
            viewers: 'PRIVATE',
            labels: ['Hop', 'Pub'],
            tags: {},
            user_id: '',
            domain_id: '',
            settings: {},
            dashboard_options: {},
            dashboard_options_schema: {},
            layouts: [],
            created_at: '',
            updated_at: '',
        },
        {
            domain_dashboard_id: '1237',
            name: 'Cafe Gondry27',
            version: 0,
            viewers: 'PRIVATE',
            labels: ['Hop', 'Pub'],
            tags: {},
            user_id: '',
            domain_id: '',
            settings: {},
            dashboard_options: {},
            dashboard_options_schema: {},
            layouts: [],
            created_at: '',
            updated_at: '',
        },
        {
            domain_dashboard_id: '1238',
            name: 'Cafe Gondry28',
            version: 0,
            viewers: 'PRIVATE',
            labels: ['Hop', 'Pub'],
            tags: {},
            user_id: '',
            domain_id: '',
            settings: {},
            dashboard_options: {},
            dashboard_options_schema: {},
            layouts: [],
            created_at: '',
            updated_at: '',
        },
        {
            domain_dashboard_id: '1239',
            name: 'Cafe Gondry29',
            version: 0,
            viewers: 'PRIVATE',
            labels: ['Hop', 'Pub'],
            tags: {},
            user_id: '',
            domain_id: '',
            settings: {},
            dashboard_options: {},
            dashboard_options_schema: {},
            layouts: [],
            created_at: '',
            updated_at: '',
        },
    ],
    projectItems: [
        {
            project_dashboard_id: '1234',
            name: 'Cafe Gondry33',
            version: 0,
            viewers: 'PUBLIC',
            labels: ['Chicken', 'Hop', 'Pub'],
            tags: {},
            user_id: '',
            domain_id: '',
            settings: {},
            dashboard_options: {},
            dashboard_options_schema: {},
            layouts: [],
            created_at: '',
            updated_at: '',
        },
        {
            project_dashboard_id: '1235',
            name: 'Cafe Gondry2',
            version: 0,
            viewers: 'PRIVATE',
            labels: ['Hop', 'Pub', 'Test', 'Test2'],
            tags: {},
            user_id: '',
            domain_id: '',
            settings: {},
            dashboard_options: {},
            dashboard_options_schema: {},
            layouts: [],
            created_at: '',
            updated_at: '',
        },
        {
            project_dashboard_id: '1235',
            name: 'Cafe Gondry21',
            version: 0,
            viewers: 'PRIVATE',
            labels: ['Hop', 'Pub', 'Test', 'Test3'],
            tags: {},
            user_id: '',
            domain_id: '',
            settings: {},
            dashboard_options: {},
            dashboard_options_schema: {},
            layouts: [],
            created_at: '',
            updated_at: '',
        },
    ],
    searchFilters: [],
    viewers: 'ALL',
    scope: 'ALL',
};

export default {
    namespaced: true,
    state: () => ({ ...state }),
    getters,
    actions,
    mutations,
};
