name: Notion Sync
on:
  workflow_dispatch:
  issues:
    types:
        [
          opened,
          edited,
          labeled,
          unlabeled,
          assigned,
          unassigned,
          milestoned,
          demilestoned,
          reopened,
          closed,
        ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Add GitHub Issues to Notion
        uses: instantish/notion-github-action@v1.2.0
        with:
          notion-token: ${{ secrets.FE_NOTION_TOKEN }}
          notion-db: ${{ secrets.FE_NOTION_ISSUE_DATABASE }}
          github-token: ${{ secrets.PAT_TOKEN }}
