import type { MenuItem } from '@/controls/context-menu/type';

export const getMenuItems = (): MenuItem[] => [
    { type: 'item', label: 'one', name: 'one' },
    { type: 'item', label: 'two', name: 'two' },
    { type: 'item', label: 'three', name: 'three' },
    { type: 'item', label: 'four', name: 'four' },
    { type: 'item', label: 'five', name: 'five' },
    { type: 'item', label: 'six', name: 'six' },
    { type: 'item', label: 'one', name: 'one' },
    { type: 'item', label: 'two', name: 'two' },
    { type: 'item', label: 'three', name: 'three' },
    { type: 'item', label: 'four', name: 'four' },
    { type: 'item', label: 'five', name: 'five' },
    { type: 'item', label: 'six', name: 'six' },
    { type: 'item', label: 'one', name: 'one' },
    { type: 'item', label: 'two', name: 'two' },
    { type: 'item', label: 'three', name: 'three' },
    { type: 'item', label: 'four', name: 'four' },
    { type: 'item', label: 'five', name: 'five' },
    { type: 'item', label: 'six', name: 'six' },
    { type: 'item', label: 'one', name: 'one' },
    { type: 'item', label: 'two', name: 'two' },
    { type: 'item', label: 'three', name: 'three' },
    { type: 'item', label: 'four', name: 'four' },
    { type: 'item', label: 'five', name: 'five' },
    { type: 'item', label: 'six', name: 'six' },
    { type: 'item', label: 'one', name: 'one' },
    { type: 'item', label: 'two', name: 'two' },
    { type: 'item', label: 'three', name: 'three' },
    { type: 'item', label: 'four', name: 'four' },
    { type: 'item', label: 'five', name: 'five' },
    { type: 'item', label: 'six', name: 'six' },
];
