export const ESCALATION_POLICY_STATE = {
    ENABLED: 'ENABLED',
    DISABLED: 'DISABLED',
};

export const ESCALATION_POLICY_FINISH_CONDITION = {
    ACKNOWLEDGED: 'ACKNOWLEDGED',
    RESOLVED: 'RESOLVED',
};
