# .github/workflows/check-pull-request.yml
name: Check Pull Request

on:
  pull_request_target:

jobs:
  check-pull-request:
    name: Check Pull Request
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - name: Check signed commits
        id: review
        uses: cloudforet-io/check-pr-action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Notify Result
        if: ${{ steps.review.outputs.signedoff == 'false' }}
        run: |
          echo "The review result is ${{ steps.review.outputs.signedoff }}"
          exit 1
