name: Deploy Vercel Preview on Comment

on:
  issue_comment:
    types: [created]

env:
  TEAM_NAME: "sulmos-projects"
  PROJECT_NAME: console
  VERCEL_TOKEN: ${{ secrets.SULMO_VERCEL_TOKEN }}

jobs:
  deploy-preview:
    if: startsWith(github.event.comment.body, '/preview')
    runs-on: ubuntu-latest

    steps:
      - name: Verify context
        id: verify
        run: |
          if [[ "${{ github.event.issue.pull_request.url }}" == "" ]]; then
            echo "🚫 This action only supports comments on PRs."
            exit 1
          fi

          COMMENTER=${{ github.event.comment.user.login }}
          echo "Commenter: $COMMENTER"
          echo "PR branch: ${{ github.head_ref }}"

      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Get PR information
        id: pr_info
        uses: actions/github-script@v6
        with:
          script: |
            const prNumber = context.issue.number;
            const { data: pullRequest } = await github.rest.pulls.get({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: prNumber
            });
            console.log('>context>>>>',JSON.stringify(context));
            console.log('>PR>>>>>',JSON.stringify(pullRequest));
            core.setOutput('reponame', pullRequest.head.repo.full_name);
            core.setOutput('branch', pullRequest.head.ref);

      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          submodules: true
          fetch-depth: 0
          repository: ${{ steps.pr_info.outputs.reponame }}
          ref: ${{ steps.pr_info.outputs.branch }}

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install Vercel CLI
        run: npm install -g vercel

      - name: Set up environment
        run: sudo apt-get install jq

      - name: Deploy to Vercel
        id: deploy
        run: |
          BRANCH_NAME=${{ steps.pr_info.outputs.branch }}
          echo "Deploying preview for branch $BRANCH_NAME"
          echo "DEPLOY_URL=$DEPLOY_URL" >> $GITHUB_ENV

      - name: Checkout Vercel Target Project
        run: vercel link --yes --scope=${{ env.TEAM_NAME }} --project=${{ env.PROJECT_NAME }} --token=${{ env.VERCEL_TOKEN }}

      - name: Pull Vercel Environment Information
        run: vercel pull --yes --token=${{ env.VERCEL_TOKEN }}

      - name: Pull Vercel Edge Config
        run: vercel env pull ./apps/web/.env --yes --token=${{ env.VERCEL_TOKEN }}

      - name: Build Project Artifacts
        run: vercel build --yes --token=${{ env.VERCEL_TOKEN }}

      - name: Deploy Project Artifacts to Vercel
        run: |
          DEPLOY_URL=$(vercel deploy --prebuilt --token=${{ env.VERCEL_TOKEN }})
          echo "DEPLOY_URL=$DEPLOY_URL" >> $GITHUB_ENV

      - name: Comment on PR
        uses: actions/github-script@v6
        with:
          script: |
            const url = process.env.DEPLOY_URL;
            const commentBody = `🚀 Preview deployed for branch \`${{ steps.pr_info.outputs.reponame }}:${{ steps.pr_info.outputs.branch }}\`: [View Preview](${url})`;
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: commentBody
            })
