name: "[PR] Review"

on:
  pull_request:
    types: [opened, synchronize, reopened]
    path-ignores:
      - '.github/**'
      - '**/deploy/**'
      - '**/skaffold.template.yaml'
      - '**/Dockerfile'
      - '**/*.dockerfile'
      - '**/*.dockerignore'
      - '**/README.md'
      - '**/LICENSE'
      - '**/AUTHORS'
      - '**/.husky/**'
      - '**/commitlint.config.js'
      - '**/.lintstagedrc.js'
    branches:
      - master
      - feature-*
    workflow_dispatch:

jobs:
  review:
    runs-on: ubuntu-latest

    env:
      TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
      TURBO_TEAM: ${{ secrets.TURBO_TEAM }}
      TURBO_API: ${{ secrets.TURBO_API }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          submodules: true
          ref: ${{ github.ref }}

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Restore cached node_modules
        id: restore-node-cache
        uses: actions/cache@v3
        with:
          path: '**/node_modules'
          key: ${{ runner.OS }}-node-modules-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.OS }}-node-modules-

      - name: Install dependencies
        if: steps.restore-node-cache.outputs.cache-hit != 'true'
        run: npm ci

      - name: Build Packages
        run: npm run build -- --filter="./packages/*" --parallel

      - name: Lint
        run: npm run lint

      - name: Test
        run: npm run test

      - name: Build Apps
        run: npm run build -- --filter="./apps/*" --parallel
