name: "[PR] Review"

on:
  pull_request:
    types: [opened, synchronize, reopened]
    path-ignores:
      - '.github/**'
      - '**/deploy/**'
      - '**/Dockerfile'
      - '**/*.dockerfile'
      - '**/*.dockerignore'
      - '**/LICENSE'
      - '**/AUTHORS'
      - '**/.husky/**'
      - '**/commitlint.config.js'
      - '**/.lintstagedrc.js'
      - '**/*.md'
      - '**/*.env'
    branches:
      - master
      - feature-*
    workflow_dispatch:


jobs:
  review:
    runs-on: ubuntu-latest
    env:
      NODE_ENV: 'development'

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          submodules: true

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Restore cached node_modules
        id: restore-node-cache
        uses: actions/cache@v3
        with:
          path: '**/node_modules'
          key: ${{ runner.OS }}-node-modules-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.OS }}-node-modules-

      - name: Install dependencies
        if: steps.restore-node-cache.outputs.cache-hit != 'true'
        run: npm ci

      - name: Make turbo cache directory
        run: mkdir -p node_modules/.cache/turbo

      - name: Download turbo artifact
        uses: actions/download-artifact@v4.1.7
        with:
          path: node_modules/.cache/turbo

      - name: Display structure of downloaded files
        run: ls -R
        working-directory: node_modules/.cache/turbo

      - name: Build Packages
        run: npm run build -- --filter="./packages/*" --parallel --output-logs=new-only

      - name: Lint
        run: npm run lint

      - name: Test
        run: npm run test

      - name: Check for TODOs in ./apps/web/
        run: |
          grep -rl "TODO" ./apps/web/ > todo_files.txt || true

      - name: Comment on Pull Request with TODO files
        if: always()
        uses: actions/github-script@v6
        with:
          github_token: ${{ secrets.PAT_TOKEN }}
          script: |
            const fs = require('fs');
            const todoFiles = fs.readFileSync('todo_files.txt', 'utf8').trim();
            if (todoFiles) {
              const filesList = todoFiles.split('\n').map(file => `- ${file}`).join('\n');
              github.rest.issues.createComment({
                issue_number: context.issue.number,
                owner: context.repo.owner,
                repo: context.repo.repo,
                body: `### 📝 TODOs Found\nThe following files contain TODOs:\n\n${filesList}`
              });
            } else {
              github.rest.issues.createComment({
                issue_number: context.issue.number,
                owner: context.repo.owner,
                repo: context.repo.repo,
                body: `### ✅ No TODOs Found\nGood job! No TODOs were found in the \`./apps/web/\` directory.`
              });
            }

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          path: node_modules/.cache/turbo/
