name: "[Pull Request] Review"

on:
  pull_request:
    types: [opened, synchronize, reopened]
    paths-ignore:
      - '.github/**'
      - '**/deploy/**'
      - '**/Dockerfile'
      - '**/*.dockerfile'
      - '**/*.dockerignore'
      - '**/LICENSE'
      - '**/AUTHORS'
      - '**/.husky/**'
      - '**/commitlint.config.js'
      - '**/.lintstagedrc.js'
      - '**/*.md'
      - '**/*.env'
    branches:
      - master
      - develop
      - feature-*
  workflow_dispatch:


jobs:
  review:
    runs-on: ubuntu-latest
    env:
      NODE_ENV: 'development'

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          submodules: true

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Restore cached node_modules
        id: restore-node-cache
        uses: actions/cache@v3
        with:
          path: '**/node_modules'
          key: ${{ runner.OS }}-node-modules-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.OS }}-node-modules-

      - name: Install dependencies
        if: steps.restore-node-cache.outputs.cache-hit != 'true'
        run: npm ci

      - name: Make turbo cache directory
        run: mkdir -p node_modules/.cache/turbo

      - name: Download turbo artifact
        uses: actions/download-artifact@v4.1.7
        with:
          path: node_modules/.cache/turbo

      - name: Display structure of downloaded files
        run: ls -R
        working-directory: node_modules/.cache/turbo

      - name: Build Packages
        run: npm run build -- --filter="./packages/*" --parallel --output-logs=new-only

      - name: Lint
        run: npm run lint

      - name: Test
        run: npm run test

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: turbo-cache
          path: node_modules/.cache/turbo/
