name: "[Push Master] Dev Release"
on:
  push:
    paths-ignore:
      - '.github/**'
      - '**/deploy/**'
      - '**/skaffold.template.yaml'
      - '**/README.md'
      - '**/LICENSE'
      - '**/AUTHORS'
      - '**/.husky/**'
      - '**/commitlint.config.js'
      - '**/.lintstagedrc.js'
    branches:
      - master

  workflow_dispatch:

jobs:
  versioning:
    if: vars.DEV_DOCKER_REPO_OWNER != null
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.calculate_version.outputs.VERSION }}
    steps:
      - name: Checkout for getting timezone
        uses: actions/checkout@v3

      - name: Calculate current date
        run: |
          sudo ln -sf /usr/share/zoneinfo/Asia/Seoul /etc/localtime
          echo "TIME=$(date +'%Y%m%d.%H%M%S')" >> $GITHUB_ENV

      - name: Calculate version
        id: calculate_version
        run: |
          echo "::set-output name=VERSION::$(cat VERSION | cut -c 2-).${{ env.TIME }}"

  docker:
    needs: versioning
    runs-on: ubuntu-latest
    env:
      VERSION: ${{ needs.versioning.outputs.version }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: true

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push to dockerhub
        uses: docker/build-push-action@v4
        env:
          BUILDKIT_COLORS: 1
        with:
          context: .
          file: ./apps/web/Dockerfile
          build-args: |
            TURBO_TOKEN=${{ secrets.TURBO_TOKEN }}
            TURBO_TEAM=${{ secrets.TURBO_TEAM }}
            TURBO_API=${{ secrets.TURBO_API }}
          push: true
          tags: |
            ${{ vars.DEV_DOCKER_REPO_OWNER }}/${{ github.event.repository.name }}:${{ env.VERSION }}
            ${{ vars.DEV_DOCKER_REPO_OWNER }}/${{ github.event.repository.name }}:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max


      - name: Slack
        if: always()
        uses: 8398a7/action-slack@v3.2.0
        with:
          status: ${{job.status}}
          fields: repo,message,commit,author,action,eventName,ref,workflow,job,took
          author_name: Github Action Slack
        env:
          SLACK_WEBHOOK_URL: ${{secrets.SLACK_WEBHOOK_URL}}
